name: Docker Image Publish

on:
  push:
    branches:
      - feat/synology-chat
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write               # 推送 GHCR 必须

    concurrency:
      group: ghcr-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 如果镜像名就用仓库名：ghcr.io/<owner>/<repo>:<tag>
      # 想固定为 we-mp-rss，也可以把 tags 改成 ghcr.io/${{ github.repository_owner }}/we-mp-rss:...

      - name: Build & Push (amd64+arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}   # eg. :feat-synology-chat
            ghcr.io/${{ github.repository }}:latest                   # 也覆盖 latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}